repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
releases:
  - name: metallb
    namespace: metallb
    chart: metallb/metallb
    version: 0.10.3
    atomic: true
    values:
      - values.yaml
