apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog-service
  namespace: blog
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: blog
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: blog
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
