apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb
  namespace: metallb
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.0.110-192.168.0.120